@server = https://evc3.onrender.com
@api = {{server}}/api/ec3
###
GET  {{server}}/api/ec3
################ Categorias: ################
###
GET {{api}}/categorias
###
POST {{api}}/categorias
Content-Type: application/json

{"nombre": "Instrumentos de Cuerda"}
################ Instrumentos: ################
###
GET {{api}}/instrumentos
###
POST {{api}}/instrumentos
Content-Type: application/json

{"nombre": "Guitarra", "categoria": "http://localhost/api/ec3/categorias/1"}
###
GET {{api}}/instrumentos/1/categoria
###
GET {{api}}/instrumentos?sort=nombre,desc